require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/projects", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Project. As you add validations to Project, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    # skip("Add a hash of attributes valid for your model")
    attributes_for(:project)
  }

  let(:invalid_attributes) {
    { project: { foo: :bar } }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ProjectsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Project.create! valid_attributes
      get projects_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end

    context 'with filters' do
      let!(:project_1) { create_project(project_budget_amount: 1) }
      let!(:project_1) { create_project(project_budget_amount: 1) }
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      project = Project.create! valid_attributes
      get project_url(project), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Project" do
        expect {
          post projects_url,
               params: { project: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Project, :count).by(1)
      end

      it "renders a JSON response with the new project" do
        post projects_url,
             params: { project: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Project" do
        expect {
          post projects_url,
               params: { project: invalid_attributes }, as: :json
        }.to change(Project, :count).by(0)
      end

      it "renders a JSON response with errors for the new project" do
        post projects_url,
             params: { project: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          total_phase_actual_spending_amount: 2000000
        }
      }

      it "updates the requested project" do
        project = Project.create! valid_attributes
        expect { 
          patch project_url(project),
              params: { project: new_attributes }, headers: valid_headers, as: :json
        }.to change { project.reload.total_phase_actual_spending_amount }.to(2000000) 
      end

      it "renders a JSON response with the project" do
        project = Project.create! valid_attributes
        patch project_url(project),
              params: { project: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not change that parameter" do
        project = Project.create! valid_attributes
        expect {
          patch project_url(project),
                params: { project: { final_estimate_of_actual_costs_through_end_of_phase_amount: 1 } }, headers: valid_headers, as: :json
        }.not_to change { project.reload.final_estimate_of_actual_costs_through_end_of_phase_amount }
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested project" do
      project = Project.create! valid_attributes
      expect {
        delete project_url(project), headers: valid_headers, as: :json
      }.to change(Project, :count).by(-1)
    end
  end
end
